Bulk Image resizer
Learn-Write-Repeat/Hacktoberfest-Contribution pull request #17
Opened 2021-10-01 15:36 UTC by Gregor-Davies

## Description

Please describe your contribution:

A simple bulk image resizer, perfect if you are working with images and machine learning. (added because of hacktober)

<hr>
Checklist

- [ x] I have added proper documentation for my contribution.
- [ x] I have added myself in `contributors.json`.
- [ x] My contribution isn't already present in the repository.
- [x] My contribution is working.
- [ x] My changes don't generate any new warnings.
- [ x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

2021-10-01 16:13 UTC, ashutoshkrris commented
Hey @Gregor-Davies 
Could you please describe your project or code more thoroughly in the README?
You can use the code to explain how it is working with examples

2021-10-02 15:08 UTC, Gregor-Davies commented
> Hey @Gregor-Davies Could you please describe your project or code more thoroughly in the README? You can use the code to explain how it is working with examples

Fixed with a little more info.

2021-10-02 19:12 UTC, arpit-dwivedi commented on contributions/Bulk-Image-Resizer/README.MD
> +A simple script to bulk resize images.
Add Title using #

2021-10-02 19:12 UTC, arpit-dwivedi commented on contributions/Bulk-Image-Resizer/README.MD
> +libraries used
Make it a heading or Bullet point

2021-10-02 19:16 UTC, arpit-dwivedi commented on contributions/Bulk-Image-Resizer/README.MD
> +How we access the image directories:
Heading or bullet.

2021-10-02 19:16 UTC, arpit-dwivedi commented on contributions/Bulk-Image-Resizer/README.MD
> +img_dir = r'Image directory'
For writing codes in the readme, [use this format](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/Markdown.md#5-coding-and-notes)

2021-10-02 19:17 UTC, arpit-dwivedi requested changes
See Inline comments

2021-10-02 19:17 UTC, arpit-dwivedi commented on contributions/Bulk-Image-Resizer/README.MD
> +	img = img.resize((80, 160)
Again, For writing codes in the readme, [use this format](https://github.com/Learn-Write-Repeat/Open-contributions/blob/master/Markdown.md#5-coding-and-notes)

2021-10-02 19:29 UTC, arpit-dwivedi approved these changes
Approved

2021-10-03 01:03 UTC, merged